"""Initial tables

Revision ID: b340bed35cb3
Revises: 
Create Date: 2026-04-14 03:31:19.491265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b340bed35cb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('monthly_fee_cents', sa.Integer(), nullable=True),
    sa.Column('overage_threshold_minutes', sa.Integer(), nullable=True),
    sa.Column('overage_rate_cents', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('retell_agent_id', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retell_agent_id')
    )
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('retell_agent_id', sa.String(length=200), nullable=True),
    sa.Column('retell_call_id', sa.String(length=200), nullable=True),
    sa.Column('from_number', sa.String(length=50), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('call_summary', sa.Text(), nullable=True),
    sa.Column('user_sentiment', sa.String(length=50), nullable=True),
    sa.Column('support_type', sa.String(length=100), nullable=True),
    sa.Column('call_successful', sa.Boolean(), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retell_call_id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('billing_period_start', sa.Date(), nullable=False),
    sa.Column('billing_period_end', sa.Date(), nullable=False),
    sa.Column('base_fee_cents', sa.Integer(), nullable=True),
    sa.Column('total_minutes', sa.Float(), nullable=True),
    sa.Column('overage_minutes', sa.Float(), nullable=True),
    sa.Column('overage_amount_cents', sa.Integer(), nullable=True),
    sa.Column('total_cents', sa.Integer(), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_payment_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    op.drop_table('calls')
    op.drop_table('agent_mappings')
    op.drop_table('clients')
    # ### end Alembic commands ###
