"""Add twilio_phone_number to clients

Revision ID: d473a90896d0
Revises: b340bed35cb3
Create Date: 2026-04-14 03:52:23.863325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd473a90896d0'
down_revision = 'b340bed35cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twilio_phone_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('twilio_phone_number')

    # ### end Alembic commands ###
